// <auto-generated />
using System;
using HMS.Bill.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS.WebAPI.Migrations.BillBookingDb
{
    [DbContext(typeof(BillBookingDbContext))]
    partial class BillBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMS.Bill.Domain.BillBillBooking", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("DiscountID")
                        .HasColumnType("int");

                    b.Property<int>("PrePayment")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionistID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID");

                    b.HasIndex("DiscountID")
                        .IsUnique();

                    b.ToTable("BillBillBooking", "bill");
                });

            modelBuilder.Entity("HMS.Bill.Domain.BillBillBookingRoom", b =>
                {
                    b.Property<int>("BillID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("BillID", "RoomID");

                    b.ToTable("BillBillBookingRoom", "bill");
                });

            modelBuilder.Entity("HMS.Bill.Domain.BillDiscount", b =>
                {
                    b.Property<int>("DiscountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountID"));

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<int>("StartDate")
                        .HasColumnType("int");

                    b.HasKey("DiscountID");

                    b.ToTable("BillDiscount", "bill");
                });

            modelBuilder.Entity("HMS.Bill.Domain.BillPayment", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillID"));

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("BillID");

                    b.ToTable("BillPayment", "bill");
                });

            modelBuilder.Entity("HMS.Bill.Domain.BillBillBooking", b =>
                {
                    b.HasOne("HMS.Bill.Domain.BillDiscount", null)
                        .WithOne()
                        .HasForeignKey("HMS.Bill.Domain.BillBillBooking", "DiscountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HMS.Bill.Domain.BillBillBookingRoom", b =>
                {
                    b.HasOne("HMS.Bill.Domain.BillBillBooking", null)
                        .WithMany()
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
