services:
  hms.webapi:
    image: ${DOCKER_REGISTRY-}hmswebapi
    build:
      context: .
      dockerfile: HMS.WebAPI/Dockerfile
    ports:
      - "6162:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=192.168.1.2;Initial Catalog=HMS_Db;User ID=sa;Password=yourStrong(!)Password;Trust Server Certificate=True  